# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53090e46aafa2abf72384f4a7aedd462d843d2d22089d575717507d45d70175d5ec7e69a1ba1dd6f6b55ec0a9056883a4f72acad7e696ff7dc35e23fa652378e

test:
  secret_key_base: 44bc39b73ad5873a9d0c92d4e07ee606a0958b47227bb292afa85222fa5a687498cacb5ff2a5162f250e3b32338a2755e63140d5149acec1e74dd874be4ce887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
